### ISSUE TITLE
Example Markdown blog post

### ISSUE THREAD

**Issue by kgrubb** [code-tribe/nuxt-netlify-cms-starter#1]
Hey, I just went through your blog tutorial and I'm a little bit stuck on the markdown formatting. I see that your blog page has h1 headers and other things of the sort, but I can't seem to get it working when i create a blog post on my local  repo. An example md file would be super awesome!

**Comment by code-tribe** [comment]
@kgrubb I was thinking that. It's a bit late here now (22:55) but if you can wait until the morning I'll create an example post. I've also worked on a couple of updates for this repository that aren't quite ready yet!

**Comment by code-tribe** [comment]
Actually, I'll update it now. Give me 5 mins!

**Comment by code-tribe** [comment]
This is now fixed. Example post added, alongside other changes and dependency updates.

**Comment by kgrubb** [comment]
Wow! That was super fast! Thank you!
