### ISSUE TITLE
Update the netlify identity widget script tag in admin/index.html

### ISSUE THREAD

**Issue by p3lican** [code-tribe/nuxt-netlify-cms-starter#2]
FYI this wouldn't build for me until I added:
  <script src="https://cdn.jsdelivr.net/npm/netlify-identity-widget@1.5.2/build/netlify-identity-widget.min.js"></script>

**Comment by code-tribe** [comment]
Thanks for this @p3lican, though I think the blog post needs changing more than anything. The identity widget won't necessarily work unless Netlify is configured properly.
